#!/usr/bin/env python3
"""Theme 4 — CatalystMind AI — narration via ElevenLabs (Jessica, playful F)."""
import os, json, urllib.request, subprocess
from pathlib import Path

API_KEY = os.environ["ELEVEN_KEY"]
VOICE_ID = "cgSgspJ2msm6clMCkdW9"  # Jessica - playful, bright, warm

UNITS = [
    "India's path to low-carbon industry runs through breakthrough catalysts - C-O-two to methanol, ethanol to jet fuel, biomass to hydrocarbons. These aren't niche research questions; they're the foundation of sustainable fuels and circular chemistry. Today, catalyst discovery is bench-scale trial-and-error. A single screening campaign takes months. Institutional knowledge sits in lab notebooks scattered across researchers and decades.",
    "CatalystMind AI is a full discovery workflow in one interface. A researcher enters a target reaction. The platform fetches known candidates from curated catalogs. A generative module proposes novel candidate designs. Predictive models rank every candidate on activity, selectivity, and stability with confidence scores. Researchers log experimental outcomes - and the platform retrains, learning from every result.",
    "Dashboard. Three target reactions tracked. Sixty-nine candidates across them - twenty-three from databases, eight generated by AI, the rest from prior experiments. Twelve experiments logged. Active model accuracy point eight three.",
    "C-O-two to methanol workbench. Twenty-three candidates ranked by predicted activity. Filter by origin: GENERATIVE underscore A-I. Eight novel designs at the top. Expand the leader: modified copper zinc oxide with niobium doping. Predicted activity ninety-one. Selectivity eighty-seven. Confidence eighty-five. Rationale shown verbatim - modified copper site improves intermediate binding. Click View 3D - interactive 3Dmol viewer renders the structure. Rotate, zoom, change render style. The kind of feedback chemists actually use.",
    "Activity-versus-selectivity scatter. Marker size encodes stability. Color-coded by origin - blue from databases, violet from generative AI. Two novel candidates outperform the best known. The plot a chemist uses to pick the next five molecules to synthesize.",
    "Experiments tab. Twelve results logged with predicted-versus-measured deltas. Tags: BEAT underscore PREDICTION, MATCHED, UNDERPERFORMED. The underperformers are gold - they show where the model is wrong. Log a new result: predicted point eight five yield, measured point nine two. Click Retrain. Toast: model v-one-point-two, accuracy point eight six. The feedback loop closed. Dashboard updates immediately.",
    "Stack: Next.js plus Prisma plus SQLite. 3Dmol-dot-js for the molecular viewer. Mock A-I uses per-reaction hardcoded catalogs and deterministic property prediction based on SMILES hashing. Production paths swap in Materials Project, Open Catalyst Project, BRENDA APIs and a real graph neural network. Same interface, same dashboard.",
    "GPS Renewables runs the country's largest biogas portfolio and just won India's first ethanol-to-jet plant bid. Twelve-week pilot proposal. Weeks one to four: integrate their reaction catalog. Weeks five to eight: shadow real experiments. Weeks nine to twelve: deliver retrained model and platform handoff. Cost: four to six lakhs. One failed catalyst batch costs more than that.",
    "CatalystMind AI. Target reaction in, ranked novel candidates out. Experimental feedback retrains the model. The platform that gets smarter with every batch.",
]

def tts(text, out_path):
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}",
        data=json.dumps({"text": text, "model_id": "eleven_multilingual_v2",
            "voice_settings": {"stability": 0.45, "similarity_boost": 0.75, "style": 0.35, "use_speaker_boost": True}}).encode(),
        headers={"xi-api-key": API_KEY, "Content-Type": "application/json", "Accept": "audio/mpeg"},
        method="POST")
    with urllib.request.urlopen(req, timeout=120) as r:
        out_path.write_bytes(r.read())

out_dir = Path("/Users/sridharsuresh/Documents/ai-for-bharat/docs/video-output/theme4/audio")
out_dir.mkdir(parents=True, exist_ok=True)
total = sum(len(u) for u in UNITS)
print(f"Voice: Jessica (playful F) · {total} chars")
for i, txt in enumerate(UNITS, 1):
    print(f"[unit {i:02d}] {len(txt)} chars")
    tts(txt, out_dir / f"unit_{i:02d}.mp3")
print("Converting MP3 → AIFF...")
for mp3 in sorted(out_dir.glob("unit_*.mp3")):
    aiff = mp3.with_suffix(".aiff")
    subprocess.run(["afconvert", "-f", "AIFF", "-d", "BEI16@44100", str(mp3), str(aiff)], check=True, capture_output=True)
print("✓ Done")
