import "dotenv/config"
import { prisma } from "../lib/db"
import { lookupKnownCandidates, generateNovelCandidates, predictProperties } from "../lib/ai"
import { CandidateOrigin, ReactionType, TrackType, ExperimentOutcome } from "../lib/enums"

function mapSource(s: string): string {
  if (s === "OCP") return "Open Catalyst Project"
  if (s === "BRENDA") return "BRENDA"
  if (s === "Materials_Project") return "Materials Project"
  return "Literature"
}

async function seedReaction(
  data: {
    name: string
    reactionType: (typeof ReactionType)[keyof typeof ReactionType]
    track: (typeof TrackType)[keyof typeof TrackType]
    description: string
    targetYield: number
  }
) {
  const reaction = await prisma.reaction.create({
    data: {
      name: data.name,
      reactionType: data.reactionType,
      track: data.track,
      description: data.description,
      targetYield: data.targetYield,
      createdBy: "Dr. Demo Researcher",
      discoveryCompleted: false,
    },
  })

  const known = await lookupKnownCandidates(data.reactionType, data.track)
  const generated = await generateNovelCandidates(data.reactionType, known, 8)
  const rows = []

  for (const k of known) {
    const pred = await predictProperties({ formula: k.formula, smiles: k.smiles }, data.reactionType)
    rows.push({
      reactionId: reaction.id,
      origin: CandidateOrigin.DATABASE_LOOKUP,
      source: mapSource(k.source),
      name: k.name,
      formula: k.formula,
      smiles: k.smiles ?? null,
      description: null,
      predictedActivity: pred.activity,
      predictedSelectivity: pred.selectivity,
      predictedStability: pred.stability,
      predictedYield: pred.yield,
      confidence: pred.confidence,
      reasoning: `Ranked from curated ${k.source} baseline; mock predictor tuned for ${data.reactionType}.`,
      propertyRationale: JSON.stringify(pred.rationale),
    })
  }
  for (const g of generated) {
    const pred = await predictProperties({ formula: g.formula, smiles: g.smiles }, data.reactionType)
    rows.push({
      reactionId: reaction.id,
      origin: CandidateOrigin.GENERATIVE_AI,
      source: "Generated by AI",
      name: g.name,
      formula: g.formula,
      smiles: g.smiles,
      description: g.variationDescription,
      predictedActivity: pred.activity,
      predictedSelectivity: pred.selectivity,
      predictedStability: pred.stability,
      predictedYield: pred.yield,
      confidence: pred.confidence,
      reasoning: `Novel design from ${g.basisCandidate ?? "pool"}: ${g.variationDescription}`,
      propertyRationale: JSON.stringify(pred.rationale),
    })
  }

  await prisma.candidate.createMany({ data: rows })
  await prisma.reaction.update({
    where: { id: reaction.id },
    data: { discoveryCompleted: true },
  })

  return reaction.id
}

async function main() {
  process.env.USE_MOCK_AI = process.env.USE_MOCK_AI ?? "true"

  await prisma.experiment.deleteMany()
  await prisma.candidate.deleteMany()
  await prisma.modelVersion.deleteMany()
  await prisma.reaction.deleteMany()

  const r1 = await seedReaction({
    name: "CO₂ to Methanol (GPS Renewables E2J pilot)",
    reactionType: ReactionType.CO2_TO_METHANOL,
    track: TrackType.CATALYSIS,
    description: "Low-temperature CO₂ hydrogenation to methanol for e-fuels integration.",
    targetYield: 42,
  })
  const r2 = await seedReaction({
    name: "Ethanol to Hydrocarbon (Sustainable Aviation Fuel)",
    reactionType: ReactionType.ETHANOL_TO_HYDROCARBON,
    track: TrackType.CATALYSIS,
    description: "Ethanol upgrading to jet-range hydrocarbons via acid-metal tandem catalysis.",
    targetYield: 55,
  })
  const r3 = await seedReaction({
    name: "Biomass Cellulose to Hydrocarbon",
    reactionType: ReactionType.CELLULOSE_TO_HYDROCARBON,
    track: TrackType.SYNTHETIC_BIOLOGY,
    description: "Enzymatic cellulose depolymerisation coupled to catalytic hydrodeoxygenation.",
    targetYield: 38,
  })

  const allCandidates = await prisma.candidate.findMany({
    orderBy: [{ reactionId: "asc" }, { predictedActivity: "desc" }],
  })

  const outcomes = [
    ExperimentOutcome.BEAT_PREDICTION,
    ExperimentOutcome.MATCHED,
    ExperimentOutcome.UNDERPERFORMED,
    ExperimentOutcome.BEAT_PREDICTION,
    ExperimentOutcome.MATCHED,
    ExperimentOutcome.INCONCLUSIVE,
    ExperimentOutcome.BEAT_PREDICTION,
    ExperimentOutcome.MATCHED,
    ExperimentOutcome.UNDERPERFORMED,
    ExperimentOutcome.MATCHED,
    ExperimentOutcome.BEAT_PREDICTION,
    ExperimentOutcome.MATCHED,
  ]

  for (let i = 0; i < 12; i++) {
    const c = allCandidates[(i * 5) % allCandidates.length]
    const dAct = (i % 4) * 0.04 - 0.02
    const dSel = (i % 3) * 0.03 - 0.03
    const dY = (i % 5) * 3 - 4
    await prisma.experiment.create({
      data: {
        candidateId: c.id,
        reactionId: c.reactionId,
        measuredActivity: Math.min(1, Math.max(0, c.predictedActivity + dAct)),
        measuredSelectivity: Math.min(1, Math.max(0, c.predictedSelectivity + dSel)),
        measuredStability: Math.min(1, Math.max(0, c.predictedStability + (i % 2) * 0.02 - 0.01)),
        measuredYield: Math.min(100, Math.max(0, c.predictedYield + dY)),
        outcome: outcomes[i]!,
        notes: i === 3 ? "Edge case: ambiguous temperature drift during ramp (demo)." : `Lab run #${i + 1} synthetic log.`,
        loggedBy: i % 2 === 0 ? "Priya Rao" : "Arjun Mehta",
      },
    })
  }

  await prisma.modelVersion.createMany({
    data: [
      {
        versionTag: "v1.0",
        experimentsUsed: 0,
        accuracyMetric: 0.78,
        notes: "Initial mock weights before lab feedback.",
        active: false,
      },
      {
        versionTag: "v1.1",
        experimentsUsed: 12,
        accuracyMetric: 0.83,
        notes: "Calibrated on first 12 bench experiments (mock).",
        active: true,
      },
    ],
  })

  const rc = await prisma.reaction.count()
  const cc = await prisma.candidate.count()
  const ec = await prisma.experiment.count()

  console.log("--- CatalystMind AI seed complete ---")
  console.log(`Reactions: ${rc} (ids: ${r1}, ${r2}, ${r3})`)
  console.log(`Candidates: ${cc} (expected 69)`)
  console.log(`Experiments: ${ec}`)
  console.log(`Model versions: 2 (active v1.1 @ 0.83 accuracy)`)
  console.log("\nRun: npm run dev  →  http://localhost:3000")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
