import { NextResponse } from "next/server"
import { prisma } from "@/lib/db"
import { lookupKnownCandidates, generateNovelCandidates, predictProperties } from "@/lib/ai"
import type { ReactionType, TrackType } from "@/lib/enums"
import { CandidateOrigin } from "@/lib/enums"

export async function POST(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params
  const reaction = await prisma.reaction.findUnique({ where: { id } })
  if (!reaction) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (reaction.discoveryCompleted) {
    return NextResponse.json({ error: "Discovery already completed for this reaction" }, { status: 409 })
  }

  const rt = reaction.reactionType as ReactionType
  const tr = reaction.track as TrackType

  const known = await lookupKnownCandidates(rt, tr)
  const generated = await generateNovelCandidates(rt, known, 8)

  const rows = []

  for (const k of known) {
    const pred = await predictProperties({ formula: k.formula, smiles: k.smiles }, rt)
    rows.push({
      reactionId: id,
      origin: CandidateOrigin.DATABASE_LOOKUP,
      source: mapSource(k.source),
      name: k.name,
      formula: k.formula,
      smiles: k.smiles ?? null,
      description: null,
      predictedActivity: pred.activity,
      predictedSelectivity: pred.selectivity,
      predictedStability: pred.stability,
      predictedYield: pred.yield,
      confidence: pred.confidence,
      reasoning: `Ranked from curated ${k.source} baseline; mock predictor tuned for ${rt}.`,
      propertyRationale: JSON.stringify(pred.rationale),
    })
  }

  for (const g of generated) {
    const pred = await predictProperties({ formula: g.formula, smiles: g.smiles }, rt)
    rows.push({
      reactionId: id,
      origin: CandidateOrigin.GENERATIVE_AI,
      source: "Generated by AI",
      name: g.name,
      formula: g.formula,
      smiles: g.smiles,
      description: g.variationDescription,
      predictedActivity: pred.activity,
      predictedSelectivity: pred.selectivity,
      predictedStability: pred.stability,
      predictedYield: pred.yield,
      confidence: pred.confidence,
      reasoning: `Novel design from ${g.basisCandidate ?? "pool"}: ${g.variationDescription}`,
      propertyRationale: JSON.stringify(pred.rationale),
    })
  }

  await prisma.$transaction([
    prisma.candidate.createMany({ data: rows }),
    prisma.reaction.update({ where: { id }, data: { discoveryCompleted: true } }),
  ])

  const ranked = await prisma.candidate.findMany({
    where: { reactionId: id },
    orderBy: { predictedActivity: "desc" },
  })

  return NextResponse.json({
    databaseMatches: known.length,
    generatedCount: generated.length,
    ranked: ranked.map((c, i) => ({ ...c, rank: i + 1 })),
  })
}

function mapSource(s: string): string {
  if (s === "OCP") return "Open Catalyst Project"
  if (s === "BRENDA") return "BRENDA"
  if (s === "Materials_Project") return "Materials Project"
  return "Literature"
}
